// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v4.24.4
// source: key-manager.proto

package key_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for Transaction Priority (p1, p2, p3)
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0 // Default value, not specified
	Priority_P1                   Priority = 1 // High priority
	Priority_P2                   Priority = 2 // Medium priority
	Priority_P3                   Priority = 3 // Low priority
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "P1",
		2: "P2",
		3: "P3",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"P1":                   1,
		"P2":                   2,
		"P3":                   3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_key_manager_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_key_manager_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{0}
}

// The transaction request sent to the submitter
type KeyManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`            // Name of the submitting application
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=Priority" json:"priority,omitempty"` // Priority of the transaction (p1, p2, p3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyManagerRequest) Reset() {
	*x = KeyManagerRequest{}
	mi := &file_key_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyManagerRequest) ProtoMessage() {}

func (x *KeyManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyManagerRequest.ProtoReflect.Descriptor instead.
func (*KeyManagerRequest) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{0}
}

func (x *KeyManagerRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *KeyManagerRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

type KeyAssigmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Status of key assignment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAssigmentResponse) Reset() {
	*x = KeyAssigmentResponse{}
	mi := &file_key_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAssigmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAssigmentResponse) ProtoMessage() {}

func (x *KeyAssigmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAssigmentResponse.ProtoReflect.Descriptor instead.
func (*KeyAssigmentResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{1}
}

func (x *KeyAssigmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type KeyFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyFetchResponse) Reset() {
	*x = KeyFetchResponse{}
	mi := &file_key_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyFetchResponse) ProtoMessage() {}

func (x *KeyFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyFetchResponse.ProtoReflect.Descriptor instead.
func (*KeyFetchResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{2}
}

func (x *KeyFetchResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KeyReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyReleaseResponse) Reset() {
	*x = KeyReleaseResponse{}
	mi := &file_key_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyReleaseResponse) ProtoMessage() {}

func (x *KeyReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyReleaseResponse.ProtoReflect.Descriptor instead.
func (*KeyReleaseResponse) Descriptor() ([]byte, []int) {
	return file_key_manager_proto_rawDescGZIP(), []int{3}
}

func (x *KeyReleaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_key_manager_proto protoreflect.FileDescriptor

var file_key_manager_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x6b, 0x65, 0x79, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x11, 0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x09, 0x2e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x22, 0x30, 0x0a, 0x14, 0x4b, 0x65, 0x79, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x10, 0x4b, 0x65, 0x79, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2e, 0x0a, 0x12,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x3c, 0x0a, 0x08,
	0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x49, 0x4f,
	0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x31, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x32,
	0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x33, 0x10, 0x03, 0x32, 0xb3, 0x01, 0x0a, 0x11, 0x4b,
	0x65, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x36, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x2e,
	0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x4b, 0x65, 0x79, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x2e, 0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x4b, 0x65, 0x79, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x2e, 0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6b, 0x65, 0x79, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_key_manager_proto_rawDescOnce sync.Once
	file_key_manager_proto_rawDescData []byte
)

func file_key_manager_proto_rawDescGZIP() []byte {
	file_key_manager_proto_rawDescOnce.Do(func() {
		file_key_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_manager_proto_rawDesc), len(file_key_manager_proto_rawDesc)))
	})
	return file_key_manager_proto_rawDescData
}

var file_key_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_key_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_key_manager_proto_goTypes = []any{
	(Priority)(0),                // 0: Priority
	(*KeyManagerRequest)(nil),    // 1: KeyManagerRequest
	(*KeyAssigmentResponse)(nil), // 2: KeyAssigmentResponse
	(*KeyFetchResponse)(nil),     // 3: KeyFetchResponse
	(*KeyReleaseResponse)(nil),   // 4: KeyReleaseResponse
}
var file_key_manager_proto_depIdxs = []int32{
	0, // 0: KeyManagerRequest.priority:type_name -> Priority
	1, // 1: KeyManagerService.AssignKey:input_type -> KeyManagerRequest
	1, // 2: KeyManagerService.GetKey:input_type -> KeyManagerRequest
	1, // 3: KeyManagerService.ReleaseKey:input_type -> KeyManagerRequest
	2, // 4: KeyManagerService.AssignKey:output_type -> KeyAssigmentResponse
	3, // 5: KeyManagerService.GetKey:output_type -> KeyFetchResponse
	4, // 6: KeyManagerService.ReleaseKey:output_type -> KeyReleaseResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_key_manager_proto_init() }
func file_key_manager_proto_init() {
	if File_key_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_manager_proto_rawDesc), len(file_key_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_manager_proto_goTypes,
		DependencyIndexes: file_key_manager_proto_depIdxs,
		EnumInfos:         file_key_manager_proto_enumTypes,
		MessageInfos:      file_key_manager_proto_msgTypes,
	}.Build()
	File_key_manager_proto = out.File
	file_key_manager_proto_goTypes = nil
	file_key_manager_proto_depIdxs = nil
}
