// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionSubmitter_SubmitTransaction_FullMethodName = "/TransactionSubmitter/SubmitTransaction"
)

// TransactionSubmitterClient is the client API for TransactionSubmitter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionSubmitterClient interface {
	// Submit a transaction and receive a unique transaction ID
	SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type transactionSubmitterClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionSubmitterClient(cc grpc.ClientConnInterface) TransactionSubmitterClient {
	return &transactionSubmitterClient{cc}
}

func (c *transactionSubmitterClient) SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, TransactionSubmitter_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionSubmitterServer is the server API for TransactionSubmitter service.
// All implementations should embed UnimplementedTransactionSubmitterServer
// for forward compatibility.
type TransactionSubmitterServer interface {
	// Submit a transaction and receive a unique transaction ID
	SubmitTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
}

// UnimplementedTransactionSubmitterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionSubmitterServer struct{}

func (UnimplementedTransactionSubmitterServer) SubmitTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedTransactionSubmitterServer) testEmbeddedByValue() {}

// UnsafeTransactionSubmitterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionSubmitterServer will
// result in compilation errors.
type UnsafeTransactionSubmitterServer interface {
	mustEmbedUnimplementedTransactionSubmitterServer()
}

func RegisterTransactionSubmitterServer(s grpc.ServiceRegistrar, srv TransactionSubmitterServer) {
	// If the following call pancis, it indicates UnimplementedTransactionSubmitterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionSubmitter_ServiceDesc, srv)
}

func _TransactionSubmitter_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionSubmitterServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionSubmitter_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionSubmitterServer).SubmitTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionSubmitter_ServiceDesc is the grpc.ServiceDesc for TransactionSubmitter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionSubmitter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TransactionSubmitter",
	HandlerType: (*TransactionSubmitterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _TransactionSubmitter_SubmitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
